url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "RANDOM BITS" # the name of your site, e.g. ACME Corp.

permalink: /:year/:month/:title
include: ['_pages']
highlighter: rouge
port: 4001
